#!/bin/bash

# Variables:
#   INTERACTIVE - don't run do.tcl, just start the shell "INTERACTIVE=1 ./run_dcompiler"
#   PAUSE       - set the pause_between_commands variable, which prompts you to continue or abort
#                 after every group of commands, this makes it easier to view the output
#                 "PAUSE=1 ./run_dcompiler"
#   NO_COLOURS  - set the no_colours variable, which disables the colourisation scripts

# delete and re-create logs dir
rm -rf logs
mkdir logs

# delete and re-create the work dir
rm -rf work
mkdir work

export dc_shell_args="-64bit -no_gui -topographical -output_log_file logs/log.txt"
export additional_vars=""

# if we are not interactive then run do.tcl, otherwise just open the shell
if [[ "$INTERACTIVE" = "" ]]; then
    export dc_shell_args="$dc_shell_args -f do.tcl"
fi

if [[ "$PAUSE" != "" ]]; then
    export additional_vars="$additional_vars set pause_between_commands 1;"
fi

if [[ "$NO_COLOURS" != "" ]]; then
    export additional_vars="$additional_vars set no_colours 1;"
fi

if [[ "$additional_vars" != "" ]]; then
    export dc_shell_args="$dc_shell_args -x \"$additional_vars\""
fi

dc_shell $dc_shell_args
