START PHYSICAL PIN CONSTRAINTS;
    {pins clk} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 140.5600};
    {pins rst_n_async} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 146.1600};
    {pins power_async[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 145.0400};
    {pins power_async[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 143.9200};
    {pins pause_n_async} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 142.8000};
    {pins lm_out} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 141.6800};
    {pins uid_variable[2]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 1} {offset 74.4800};
    {pins uid_variable[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 1} {offset 73.3600};
    {pins uid_variable[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 1} {offset 72.2400};
    {pins sens_config[2]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 94.6400};
    {pins sens_config[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 95.7600};
    {pins sens_config[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 96.8800};
    {pins sens_enable} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 93.5200};
    {pins sens_read} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 92.4000};
    {pins adc_enable} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 201.6000};
    {pins adc_read} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 200.4800};
    {pins adc_conversion_complete} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 202.7200};
    {pins adc_value[15]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 180.8800};
    {pins adc_value[14]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 182.0000};
    {pins adc_value[13]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 183.1200};
    {pins adc_value[12]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 184.2400};
    {pins adc_value[11]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 185.3600};
    {pins adc_value[10]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 186.4800};
    {pins adc_value[9]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 188.7200};
    {pins adc_value[8]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 189.8400};
    {pins adc_value[7]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 190.9600};
    {pins adc_value[6]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 192.0800};
    {pins adc_value[5]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 193.2000};
    {pins adc_value[4]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 194.3200};
    {pins adc_value[3]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 195.4400};
    {pins adc_value[2]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 197.1200};
    {pins adc_value[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 198.2400};
    {pins adc_value[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 199.3600};
END PHYSICAL PIN CONSTRAINTS;

