START PHYSICAL PIN CONSTRAINTS;
    {pins clk} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 130.3000};
    {pins rst_n_async} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 135.9000};
    {pins power_async[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 134.7800};
    {pins power_async[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 133.6600};
    {pins pause_n_async} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 132.5400};
    {pins lm_out} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET4} {sides 2} {offset 131.4200};
    {pins uid_variable[2]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 1} {offset 57.5000};
    {pins uid_variable[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 1} {offset 56.3800};
    {pins uid_variable[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 1} {offset 55.2600};
    {pins sens_config[2]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 97.2600};
    {pins sens_config[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 98.3800};
    {pins sens_config[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 99.5000};
    {pins sens_enable} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 96.1400};
    {pins sens_read} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 95.0200};
    {pins adc_enable} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 181.2600};
    {pins adc_read} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 180.1400};
    {pins adc_conversion_complete} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 182.3800};
    {pins adc_value[15]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 160.5400};
    {pins adc_value[14]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 161.6600};
    {pins adc_value[13]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 162.7800};
    {pins adc_value[12]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 163.9000};
    {pins adc_value[11]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 165.0200};
    {pins adc_value[10]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 167.2600};
    {pins adc_value[9]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 168.3800};
    {pins adc_value[8]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 169.5000};
    {pins adc_value[7]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 170.6200};
    {pins adc_value[6]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 171.7400};
    {pins adc_value[5]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 172.8600};
    {pins adc_value[4]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 173.9800};
    {pins adc_value[3]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 175.6600};
    {pins adc_value[2]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 176.7800};
    {pins adc_value[1]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 177.9000};
    {pins adc_value[0]} {reference radiation_sensor_digital_top_FDT_TIMING_ADJUST0_SENSOR_VERSION1_ADC_VERSION1} {layers MET3} {sides 3} {offset 179.0200};
END PHYSICAL PIN CONSTRAINTS;

